version: "3.8"

services:
    backend:
        build:
            context: ./backend
        container_name: insider-backend
        volumes:
            - ./backend:/var/www
        working_dir: /var/www
        depends_on:
            - mysql
        restart: always

    nginx:
        image: nginx:alpine
        ports:
            - "8001:8001"
        volumes:
            - ./backend:/var/www
            - ./backend/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend

    mysql:
        image: mysql:8.0
        container_name: insider-mysql
        volumes:
            - mysql-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: insider
            MYSQL_USER: insider
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"

    frontend:
        build:
            context: ./frontend
        container_name: insider-frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules

volumes:
    mysql-data:
